2025-03-11 15:31:29,203 [DEBUG] Initializing pyfuse3
2025-03-11 15:31:29,203 [DEBUG] Calling fuse_session_new
2025-03-11 15:31:29,203 [DEBUG] Calling fuse_session_mount
2025-03-11 15:31:29,206 [INFO] FUSE filesystem mounted on '/mnt/httpfs'
2025-03-11 15:31:29,206 [INFO] Update server listening on port 9000
2025-03-11 15:31:29,207 [DEBUG] pyfuse-02: No tasks waiting, starting another worker (now 2 total).
